import 'dotenv/config';
import * as sb from './src/lib/supabase.js';
import { integrationRepository } from './src/repositories/integration.repository.js';
import { syncOneOrg } from './src/lib/integrations/gohighlevel-sync.js';
const { data: row } = await sb.serviceClient.from('integrations').select('organisation_id').eq('provider','gohighlevel').limit(1).maybeSingle();
const org=row.organisation_id;
const integ = await integrationRepository.getByProvider(org,'gohighlevel');
const res = await syncOneOrg(org, integ, ()=>{}, { full:false });
console.log('RESYNC:', JSON.stringify(res));
const fresh = await integrationRepository.getByProvider(org,'gohighlevel');
console.log('pipelines cached:', (fresh.config?.pipelines??[]).map(p=>`${p.name}(${(p.stages??[]).length} stages)`).join(', ') || 'none');
const { data: lead } = await sb.serviceClient.from('leads').select('ghl_pipeline_id,ghl_pipeline_stage_id,ghl_stage_name').eq('organisation_id',org).eq('source','gohighlevel').not('ghl_pipeline_stage_id','is',null).limit(1).maybeSingle();
console.log('sample lead stage:', JSON.stringify(lead));
process.exit(0);
