'use client';
import { useState, useRef, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { visibleNavSections, type Permissions } from '@/lib/permissions';
import { useMe } from '@/hooks/useMe';
import { AgencyDialog } from '@/features/agency/components/AgencyDialog';
import { AccountPicker } from '@/features/agency/components/AccountPicker';
import { useSidebar, HamburgerIcon } from '@/components/layout/sidebar-context';

// Sidebar — the app shell's primary navigation.
//
// NAV mirrors preview/elevate-dental-os-v2.html `const NAV` (11 sections).
// Frozen Phase-0 primitive: section agents add screens behind these routes,
// they do not edit this file.
//
// RBAC: nav visibility is driven entirely by the effective permissions the
// backend returns from GET /auth/me (.permissions, a { key: boolean } map
// over the fixed catalogue). Each route id maps to a permission key in the
// shared lib/permissions module; an item shows only when its key is true.
// Overview routes have no key and are always visible. If /auth/me fails we
// treat the user as having no permissions (only Overview shows).

// Per-section stroke icons (lucide-style, 24-grid). Keeps the visual language
// on-theme — no new deps, inherits currentColor from the section header.
const SECTION_ICONS: Record<string, string> = {
  Overview: 'M4 5h6v6H4zM14 5h6v4h-6zM14 13h6v6h-6zM4 15h6v4H4z',
  Finance: 'M12 3v18M8 7h6a3 3 0 0 1 0 6H6m0 4h8',
  'Business Health': 'M3 12h4l2 5 4-12 2 7h6',
  Operations: 'M8 2v4M16 2v4M3 9h18M5 5h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2z',
  Growth: 'M3 17l6-6 4 4 7-7M14 8h7v7',
  'Elevate CRM': 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',
  Wealth: 'M3 21h18M5 21V10l7-5 7 5v11M9 21v-6h6v6',
  Training: 'M22 10L12 5 2 10l10 5 10-5zM6 12v5c0 1 2.7 2.5 6 2.5s6-1.5 6-2.5v-5',
  System: 'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-2.92.68 2 2 0 1 1-3.96 0 1.65 1.65 0 0 0-2.92-.68 2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.6 15a2 2 0 1 1 0-3.96 1.65 1.65 0 0 0-.68-2.92 2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 2.92-.68 2 2 0 1 1 3.96 0 1.65 1.65 0 0 0 2.92.68 2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0 .42 2.74z',
  'Data Room': 'M4 6c0-1.7 3.6-3 8-3s8 1.3 8 3-3.6 3-8 3-8-1.3-8-3zM4 6v6c0 1.7 3.6 3 8 3s8-1.3 8-3V6M4 12v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6',
};

function SectionIcon({ label }: { label: string }) {
  const d = SECTION_ICONS[label];
  if (!d) return null;
  return (
    <svg
      width="15"
      height="15"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.9"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="shrink-0"
      aria-hidden="true"
    >
      <path d={d} />
    </svg>
  );
}

function initials(name: string): string {
  return name
    .split(/[\s@.]+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((p) => p[0]?.toUpperCase())
    .join('');
}

const MIN_W = 208;
const MAX_W = 384;
const DEFAULT_W = 256;
const WIDTH_KEY = 'sidebar:w';

export function Sidebar() {
  const pathname = usePathname();
  const { data: me } = useMe();

  const { collapsed, toggle: toggleCollapsed } = useSidebar();

  // Drag-to-resize width. Persisted to localStorage; clamped MIN..MAX.
  const [width, setWidth] = useState(DEFAULT_W);
  const [dragging, setDragging] = useState(false);

  useEffect(() => {
    const saved = Number(localStorage.getItem(WIDTH_KEY));
    if (saved >= MIN_W && saved <= MAX_W) setWidth(saved);
  }, []);

  const onMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    setDragging(true);
  }, []);

  useEffect(() => {
    if (!dragging) return;
    const onMove = (e: MouseEvent) => {
      const w = Math.min(MAX_W, Math.max(MIN_W, e.clientX));
      setWidth(w);
    };
    const onUp = () => {
      setDragging(false);
      setWidth((w) => {
        localStorage.setItem(WIDTH_KEY, String(w));
        return w;
      });
    };
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
    return () => {
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseup', onUp);
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    };
  }, [dragging]);

  const role = me?.role || 'reception';
  // Effective permissions from /auth/me. If the call failed (me === null),
  // permissions is null and only Overview routes resolve as visible.
  const permissions: Permissions | null = me?.permissions ?? null;

  const displayName = me?.full_name || me?.email || '';

  return (
    <aside
      style={{
        width: collapsed ? 0 : width,
        transition: dragging ? 'none' : 'width 0.18s ease',
      }}
      className={`relative shrink-0 bg-card h-screen sticky top-0 flex flex-col overflow-hidden ${
        collapsed ? 'border-0' : 'border-r border-border'
      }`}
    >
      {/* Brand header */}
      <div className="px-4 py-4 border-b border-border flex items-center gap-2.5">
        <div className="w-9 h-9 shrink-0 rounded-xl bg-gradient-to-br from-brand to-brand-700 text-white flex items-center justify-center font-display font-bold text-lg shadow-panel-sm">
          E
        </div>
        <Link href="/business-hub" className="leading-tight min-w-0 flex-1">
          <span className="block font-display text-[17px] font-semibold text-ink">Elevate</span>
          <span className="block text-[11px] uppercase tracking-[0.14em] text-ink-muted">
            Dental OS
          </span>
        </Link>
        <button
          onClick={toggleCollapsed}
          aria-label="Collapse sidebar"
          title="Collapse sidebar"
          className="shrink-0 w-8 h-8 -mr-1 rounded-lg text-ink-muted hover:text-brand hover:bg-bg flex items-center justify-center transition"
        >
          <HamburgerIcon />
        </button>
      </div>

      {/* Account switcher — agency actors only. Top-left, GHL-style: opens the
          one dialog that switches into a sub-account and manages it. */}
      <AgencyDialog />

      {/* Account picker — only for a login that belongs to several accounts.
          Separate from the agency dialog above: these are accounts the person
          is a MEMBER of, not sub-accounts they administer. */}
      <AccountPicker />

      {/* User card */}
      {me && (
        <div className="mx-3 mt-3 px-3 py-2.5 bg-bg rounded-xl flex items-center gap-2.5">
          <div className="w-8 h-8 shrink-0 rounded-full bg-brand-50 text-brand flex items-center justify-center text-xs font-semibold ring-1 ring-brand-100">
            {initials(displayName) || 'U'}
          </div>
          <div className="min-w-0">
            <div className="text-[13px] font-semibold text-ink truncate">{displayName}</div>
            <div className="text-[11px] text-ink-muted capitalize">{role.replace('_', ' ')}</div>
          </div>
        </div>
      )}

      {/* Nav — one row per section. The section's screens are not listed here;
          they are the tab strip at the top of the content area (SectionTabs),
          so this list stays one level deep however many screens a section
          grows. A row lands on the section's first VISIBLE item, so RBAC
          still decides where the click goes. */}
      <nav className="flex-1 overflow-y-auto p-3 space-y-0.5">
        {visibleNavSections(me?.role, permissions, me?.features).map((section) => {
          const active = section.items.some((i) => pathname === `/${i.id}`);
          const hasNew = section.items.some((i) => i.isNew);
          return (
            <Link
              key={section.label}
              href={`/${section.items[0].id}`}
              aria-current={active ? 'page' : undefined}
              className={`group relative flex items-center gap-2.5 rounded-lg px-3 py-2 text-[13px] transition-colors duration-150 ${
                active
                  ? 'bg-brand-50 font-semibold text-brand'
                  : 'font-medium text-ink-muted hover:bg-bg hover:text-ink'
              }`}
            >
              {/* active rail */}
              <span
                className={`absolute left-0 top-1/2 w-0.5 -translate-y-1/2 rounded-full bg-brand transition-all duration-150 ${
                  active ? 'h-5 opacity-100' : 'h-0 opacity-0 group-hover:h-3 group-hover:opacity-40'
                }`}
              />
              <SectionIcon label={section.label} />
              <span className="min-w-0 flex-1 truncate">{section.label}</span>
              {hasNew && !active && (
                <span className="ml-auto h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
              )}
            </Link>
          );
        })}
      </nav>

      {/* Drag handle — stretch sidebar width */}
      {!collapsed && (
        <div
          role="separator"
          aria-orientation="vertical"
          onMouseDown={onMouseDown}
          onDoubleClick={() => {
            setWidth(DEFAULT_W);
            localStorage.setItem(WIDTH_KEY, String(DEFAULT_W));
          }}
          title="Drag to resize · double-click to reset"
          className="group absolute top-0 right-0 h-full w-1.5 translate-x-1/2 cursor-col-resize z-10"
        >
          <span
            className={`absolute inset-y-0 left-1/2 -translate-x-1/2 w-px transition-colors ${
              dragging ? 'bg-brand w-0.5' : 'bg-transparent group-hover:bg-brand-200'
            }`}
          />
        </div>
      )}
    </aside>
  );
}
