'use client';
import { useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { canAccessRoute, type Permissions } from '@/lib/permissions';
import { NAV, type NavItem, type NavSection } from '@/lib/nav';
import { useMe } from '@/hooks/useMe';

// Sidebar — the app shell's primary navigation.
//
// NAV mirrors preview/elevate-dental-os-v2.html `const NAV` (11 sections).
// Frozen Phase-0 primitive: section agents add screens behind these routes,
// they do not edit this file.
//
// RBAC: nav visibility is driven entirely by the effective permissions the
// backend returns from GET /auth/me (.permissions, a { key: boolean } map
// over the fixed catalogue). Each route id maps to a permission key in the
// shared lib/permissions module; an item shows only when its key is true.
// Overview routes have no key and are always visible. If /auth/me fails we
// treat the user as having no permissions (only Overview shows).

export function Sidebar() {
  const pathname = usePathname();
  const { data: me } = useMe();
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({});

  const role = me?.role || 'reception';
  // Effective permissions from /auth/me. If the call failed (me === null),
  // permissions is null and only Overview routes resolve as visible.
  const permissions: Permissions | null = me?.permissions ?? null;

  // True when an individual item should render for the effective permissions.
  function canSeeItem(item: NavItem): boolean {
    return canAccessRoute(item.id, permissions);
  }

  // A section renders only when at least one of its items is visible.
  function canSeeSection(s: NavSection): boolean {
    return s.items.some(canSeeItem);
  }

  // Resolve a section's open/closed state: explicit toggle wins, else open
  // if it contains the active route, else open Overview + CRM by default.
  function sectionOpen(label: string, hasActive: boolean): boolean {
    if (label in openSections) return openSections[label];
    if (hasActive) return true;
    return label === 'Overview' || label === 'Elevate CRM';
  }

  return (
    <aside className="w-64 bg-card border-r border-border h-screen sticky top-0 overflow-y-auto">
      <div className="p-4 border-b border-border flex items-center gap-2">
        <div className="w-8 h-8 rounded-md bg-brand text-white flex items-center justify-center font-display font-bold">
          E
        </div>
        <Link href="/dashboard" className="font-display text-lg font-semibold text-ink">
          Elevate <span className="text-ink-muted font-normal">Dental OS</span>
        </Link>
      </div>

      {me && (
        <div className="px-3 py-2 mx-3 mt-3 bg-bg rounded-lg text-xs">
          <div className="font-semibold text-ink">{me.full_name || me.email}</div>
          <div className="text-ink-muted capitalize">{role.replace('_', ' ')}</div>
        </div>
      )}

      <nav className="p-3 space-y-1">
        {NAV.filter(canSeeSection).map((section) => {
          const items = section.items.filter(canSeeItem);
          if (items.length === 0) return null;
          const hasActive = items.some((i) => pathname === `/${i.id}`);
          const open = sectionOpen(section.label, hasActive);
          return (
            <div key={section.label}>
              <button
                onClick={() =>
                  setOpenSections((s) => ({ ...s, [section.label]: !open }))
                }
                className="w-full text-left text-[11px] uppercase tracking-wider font-semibold text-ink-muted px-3 py-2 flex justify-between items-center hover:text-ink"
              >
                <span>{section.label}</span>
                <span
                  className="text-[9px]"
                  style={{
                    transform: open ? 'rotate(90deg)' : 'none',
                    transition: 'transform 0.15s',
                  }}
                >
                  ▶
                </span>
              </button>
              {open &&
                items.map((item) => {
                  const active = pathname === `/${item.id}`;
                  return (
                    <Link
                      key={item.id}
                      href={`/${item.id}`}
                      aria-current={active ? 'page' : undefined}
                      className={`flex items-center gap-2 px-6 py-2 text-sm rounded-lg mx-2 transition ${
                        active
                          ? 'bg-brand-50 text-brand font-medium'
                          : 'text-ink-muted hover:bg-bg hover:text-ink'
                      }`}
                    >
                      <span>{item.label}</span>
                      {item.isNew && (
                        <span className="text-[9px] font-bold uppercase tracking-wide text-emerald-600 bg-emerald-50 rounded px-1 py-0.5">
                          New
                        </span>
                      )}
                    </Link>
                  );
                })}
            </div>
          );
        })}
      </nav>
    </aside>
  );
}
